### ISSUE TITLE
only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by DheerajAluru** [dimitrs/CLTree#1]
I have directly cloned the repo and tested it out and this is the error am facing

the output is as follows:
---------------------------------

----------------
Clustering      
----------------
read 1595 instances from test/D05.arff
attribute names: [('id', <class 'float'>), ('class', <class 'float'>), ('dim0', <class 'float'>), ('dim1', <class 'float'>), ('dim2', <class 'float'>), ('dim3', <class 'float'>), ('dim4', <class 'float'>)]
class names: ['100', '701', '101', '201', '200', '601', '501', '401', '300', '301', '302', '-1']
Traceback (most recent call last):

  File "<ipython-input-3-6a8f9ab6415b>", line 1, in <module>
    runfile('E:/Machine Learning/CLTree/cltree.py', wdir='E:/Machine Learning/CLTree')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Machine Learning/CLTree/cltree.py", line 78, in <module>
    cltree.buildTree()

  File "E:/Machine Learning/CLTree/cltree.py", line 18, in buildTree
    self.root = b.build(self.dataset)

  File "E:\Machine Learning\CLTree\build.py", line 19, in build
    self._build_tree(dataset, None, 0)

  File "E:\Machine Learning\CLTree\build.py", line 33, in _build_tree
    lhs_dataset, rhs_dataset = self._splitDatasetUsingBestCut(dataset, bestCut)

  File "E:\Machine Learning\CLTree\build.py", line 49, in _splitDatasetUsingBestCut
    lhs_set, rhs_set = self.datasetSplitter.split(dataset, bestCut.attribute, bestCut.value, idx+1)

  File "E:\Machine Learning\CLTree\build.py", line 125, in split
    **l = dataset.instance_values[0:idx]**

TypeError: only integer scalar arrays can be converted to a scalar index
----------------------------------------------------------------------------
can anyone help me in solving the error?

**Comment by EmanuelFontelles** [comment]
I solved this problem and a make a pull request. Try to see pull request session to verify the changes
